version: "3"
  
services:
  calibre:
      image: lscr.io/linuxserver/calibre:latest
      container_name: calibre
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Atehns
      volumes:
        - /home/server/data/calibre:/config
      ports:
        - 8180:8080
        - 8181:8081
      restart: unless-stopped
  
  jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Athens
        - JELLYFIN_PublishedServerUrl=192.168.1.9 #optional
      volumes:
        - /home/server/data/jellyfin:/config
        - /srv/exports/media/shows:/data/shows
        - /srv/exports/media/movies:/data/movies
        - /srv/exports/:/data/exports
      ports:
        - 8096:8096
        - 8920:8920 #optional
        - 7359:7359/udp #optional
        - 1900:1900/udp #optional
      restart: unless-stopped
