version: "3"
  
services:

  jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Athens
        - JELLYFIN_PublishedServerUrl=192.168.1.9 #optional
      volumes:
        - /home/server/data/jellyfin:/config
        - /srv/exports/media/shows:/data/shows
        - /srv/exports/media/movies:/data/movies
        - /srv/exports/:/data/exports
      ports:
        - 8096:8096
        - 8920:8920 #optional
        - 7359:7359/udp #optional
        - 1900:1900/udp #optional
      restart: unless-stopped

  icecast:
    image: pltnk/icecast2
    container_name: icecast2
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /home/server/data/icecast:/etc/icecast2
