version: "3"

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Athens'
      WEBPASSWORD: 'admin'
    # Volumes store your data between container upgrades
    volumes:
      - /home/server/data/pihole:/etc/pihole
      - /home/server/data/pihole/dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped


  cgit:
    image: invokr/cgit 
    container_name: cgit
    ports:
      - 8070:80
    volumes:
      - /srv/git:/git
      - /home/server/data/cgit/config/cgitrc:/etc/cgitrc
    restart: unless-stopped


  nginx:
      image: lscr.io/linuxserver/nginx:latest
      container_name: nginx
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - /home/server/data/nginx:/config
      ports:
        - 80:80
        - 443:443
      depends_on:
        - cgit
        - jellyfin
        - pihole
      restart: unless-stopped


  taskd:
      image: x4121/taskd:latest
      container_name: taskd
      volumes:
          - /home/server/data/taskd:/var/taskd
      ports:
          - 53589:53589
      environment:
          CERT_CN: "task.home.xyz"
          CERT_ORGANIZATION: "home"
          CERT_COUNTRY: "GR"
          CERT_STATE: "Patras"
          CERT_LOCALITY: "Greek"
      restart: unless-stopped

  radicale:
      image: xlrl/radicale:latest
      container_name: radicale
      environment: 
        # - GIT_REPOSITORY=https://user:password@github.com/user/repo
        # - GIT_USERNAME=username
        # - GIT_EMAIL=usermail@mail.com
        - RADICALE_USER=admin
        - RADICALE_PASS=admin
      ports: 
        - "8989:8000"
      volumes: 
        - /home/server/data/radicale:/var/radicale
